### ISSUE TITLE
할 일

### ISSUE THREAD

**Issue by sohndohyun** [42seoul-NULL/Terminvader#3]
기본
- [x] 미션 진행에 대한 일정표
- [x] 일정에 대한 상세 활동 일지
- [x] 작업 시간 및 학습 일지

subject 0
- [x] 개발 일정과 리소스 배분
- [x] 이슈 트레킹 어떻게 할지
- [x] 마무리 된 이슈 개발 일지 형태 문서화

subject 1
- [x] 개발 언어 리서치
- [x] 통합개발환경 리서치
- [x] 버전관리 툴 리서치

subject 2
- [x] 키보드 입력 처리하기 위한 메서드 선정
- [x] 키 입력 구현
- [x] 객체 관리 자료구조
- [ ] 메모리 관리 방식

**Comment by hopark123** [comment]
all celar
